/**
 * Document Template Registry
 * fillMethod:
 *   - "support-sheet"  → NoQueue preparation sheet (NON-OFFICIAL)
 *   - "coordinates"    → text overlay on official PDF
 *   - "acroform"       → fill AcroForm fields on official PDF
 *
 * LEGAL: If official source says the form is completed at the counter by the clerk,
 * fillMethod MUST be "support-sheet". Never fake an official form.
 */

export const templateRegistry = {

  // ─── IDENTITY CARD ──────────────────────────────────────────────────────────

  "cerere-ci-reinnoire": {
    id: "cerere-ci-reinnoire",
    title: "Identity Card Renewal — Preparation Sheet",
    titleRo: "Reînnoire act de identitate — fișă pregătire",
    category: "id-renewal",
    institution: "SPCLEP Cluj-Napoca",
    sourceUrl: "https://mai.gov.ro/servicii/acte-de-identitate/",
    runtimeTemplateUrl: null,
    sourceType: "official_page",
    isOfficialSource: true,
    isOfficialSubmittable: false,
    // The form is completed by the SPCLEP clerk at the counter — support-sheet only
    fillMethod: "support-sheet",
    profileFieldMap: {
      last_name: "last_name", first_name: "first_name", cnp: "cnp",
      birth_date: "birth_date", birth_place: "birth_place",
      address_line_1: "address_line_1", city: "city", county: "county",
      id_series: "id_series", id_number: "id_number",
      id_issued_by: "id_issued_by", id_expiry_date: "id_expiry_date",
      father_name: "father_name", mother_name: "mother_name",
    },
    requiredProfileFields: ["first_name", "last_name", "cnp", "birth_date", "address_line_1", "city"],
    requiredAssets: [],
    requiredAttachments: [
      "Birth certificate (original + copy)",
      "Old ID card (expired or to be changed)",
      "Proof of residence (contract / utility bill / owner declaration)",
      "Payment — 7 RON tax stamp (timbru fiscal)",
    ],
    signatureMode: "required",
    photoMode: "none",
    instructionsShort: "Go to SPCLEP Cluj-Napoca, Str. Constanța nr. 5. The application is completed by the clerk. Arrive before 08:30 to avoid long queues.",
    needsNotary: false,
    needsPhysicalPresence: true,
    needsAppointment: false,
    needsManualReview: false,
    outputFormats: ["pdf"],
    templateVersion: "2024",
    lastVerifiedAt: "2024-01-01",
  },

  "cerere-ci-pierdut": {
    id: "cerere-ci-pierdut",
    title: "Lost / Stolen ID Card — Preparation Sheet",
    titleRo: "CI pierdut/furat — fișă pregătire",
    category: "lost-id",
    institution: "SPCLEP Cluj-Napoca",
    sourceUrl: "https://mai.gov.ro/servicii/acte-de-identitate/",
    runtimeTemplateUrl: null,
    sourceType: "official_page",
    isOfficialSource: true,
    isOfficialSubmittable: false,
    fillMethod: "support-sheet",
    profileFieldMap: {
      last_name: "last_name", first_name: "first_name", cnp: "cnp",
      birth_date: "birth_date", address_line_1: "address_line_1", city: "city",
    },
    requiredProfileFields: ["first_name", "last_name", "cnp", "birth_date", "address_line_1"],
    requiredAssets: [],
    requiredAttachments: [
      "Police loss/theft declaration (from any IPJ Cluj precinct — free)",
      "Birth certificate (original + copy)",
      "Proof of residence (if address changed)",
      "Payment — 7 RON standard / 50 RON urgent (72h)",
    ],
    signatureMode: "required",
    photoMode: "none",
    instructionsShort: "Step 1: File a police declaration at any IPJ Cluj precinct (Calea Dorobanților 9 or local). Step 2: Bring police declaration + documents to SPCLEP.",
    needsNotary: false,
    needsPhysicalPresence: true,
    needsAppointment: false,
    needsManualReview: false,
    outputFormats: ["pdf"],
    templateVersion: "2024",
    lastVerifiedAt: "2024-01-01",
  },

  "cerere-ci-domiciliu": {
    id: "cerere-ci-domiciliu",
    title: "Address / Domicile Change — Preparation Sheet",
    titleRo: "Schimbare domiciliu/reședință — fișă pregătire",
    category: "domicile-change",
    institution: "SPCLEP Cluj-Napoca",
    sourceUrl: "https://mai.gov.ro/servicii/acte-de-identitate/",
    runtimeTemplateUrl: null,
    sourceType: "official_page",
    isOfficialSource: true,
    isOfficialSubmittable: false,
    fillMethod: "support-sheet",
    profileFieldMap: {
      last_name: "last_name", first_name: "first_name", cnp: "cnp",
      birth_date: "birth_date", address_line_1: "address_line_1", city: "city", county: "county",
    },
    requiredProfileFields: ["first_name", "last_name", "cnp", "address_line_1", "city"],
    requiredAssets: [],
    requiredAttachments: [
      "Current ID card",
      "Proof of new address: lease contract / utility bill / owner's notarized declaration",
      "If renting: owner's ID copy + signed hosting declaration",
      "Payment — 7 RON tax stamp",
    ],
    signatureMode: "required",
    photoMode: "none",
    instructionsShort: "Visit SPCLEP in the district where your NEW address is located. The application is completed by the clerk at the counter.",
    needsNotary: false,
    needsPhysicalPresence: true,
    needsAppointment: false,
    needsManualReview: false,
    outputFormats: ["pdf"],
    templateVersion: "2024",
    lastVerifiedAt: "2024-01-01",
  },

  // ─── PASSPORT ───────────────────────────────────────────────────────────────

  "cerere-pasaport": {
    id: "cerere-pasaport",
    title: "Standard Passport Application — Preparation Sheet",
    titleRo: "Cerere pașaport simplu electronic — fișă pregătire",
    category: "passport",
    institution: "Serviciul Pașapoarte Cluj",
    sourceUrl: "https://www.epasapoarte.ro",
    runtimeTemplateUrl: null,
    sourceType: "official_page",
    isOfficialSource: true,
    // The passport application is completed by the PASSPORT WORKER in the computer system,
    // NOT by the citizen at home. Generating an official-looking form would be deceptive.
    isOfficialSubmittable: false,
    fillMethod: "support-sheet",
    profileFieldMap: {
      last_name: "last_name", first_name: "first_name", cnp: "cnp",
      birth_date: "birth_date", birth_place: "birth_place",
      id_series: "id_series", id_number: "id_number", id_issued_by: "id_issued_by",
    },
    requiredProfileFields: ["first_name", "last_name", "cnp", "birth_date", "birth_place", "id_series", "id_number"],
    requiredAssets: [],
    requiredAttachments: [
      "Valid identity card (CI/BI) — original",
      "Old passport (if renewal, to be cancelled)",
      "Payment proof — 258 RON (10-year adult) / 134 RON (under 14)",
      "For minors: both parents' presence + notarized consent if one parent absent",
    ],
    signatureMode: "required",
    photoMode: "required",
    instructionsShort: "Book appointment at epasapoarte.ro. Pay at CEC Bank before your appointment. The form is completed by the officer — bring this sheet as a checklist.",
    needsNotary: false,
    needsPhysicalPresence: true,
    needsAppointment: true,
    needsManualReview: false,
    onlineUrl: "https://www.epasapoarte.ro",
    outputFormats: ["pdf"],
    templateVersion: "2024",
    lastVerifiedAt: "2024-01-01",
  },

  "cerere-pasaport-urgent": {
    id: "cerere-pasaport-urgent",
    title: "ePașapoarte Appointment — Preparation Sheet",
    titleRo: "Programare ePașapoarte — fișă pregătire",
    category: "passport-urgent",
    institution: "Serviciul Pașapoarte Cluj / DGPAS",
    sourceUrl: "https://www.epasapoarte.ro",
    runtimeTemplateUrl: null,
    sourceType: "official_page",
    isOfficialSource: true,
    isOfficialSubmittable: false,
    fillMethod: "support-sheet",
    profileFieldMap: {
      last_name: "last_name", first_name: "first_name", cnp: "cnp",
      birth_date: "birth_date", id_series: "id_series", id_number: "id_number",
    },
    requiredProfileFields: ["first_name", "last_name", "cnp"],
    requiredAssets: [],
    requiredAttachments: [
      "Valid identity card — original",
      "Proof of urgency (ticket, medical document, etc.)",
      "Payment — 804 RON urgent (3 working days) / 258 RON standard",
    ],
    signatureMode: "none",
    photoMode: "required",
    instructionsShort: "Schedule at epasapoarte.ro. Urgent passports are issued in 3 working days. Pay at CEC Bank. Bring this sheet as a checklist.",
    needsNotary: false,
    needsPhysicalPresence: true,
    needsAppointment: true,
    needsManualReview: false,
    onlineUrl: "https://www.epasapoarte.ro",
    outputFormats: ["pdf"],
    templateVersion: "2024",
    lastVerifiedAt: "2024-01-01",
  },

  // ─── OFFICIAL DGP FORMS (coordinate fill) ───────────────────────────────────

  "cerere-istoric-pasaport": {
    id: "cerere-istoric-pasaport",
    title: "Passport History Request",
    titleRo: "Cerere furnizare date din evidența pașapoartelor",
    category: "passport-history",
    institution: "Direcția Generală de Pașapoarte",
    sourceUrl: "https://www.mai.gov.ro/wp-content/uploads/2021/06/Cerere-furnizare-date-din-evidenta-pasapoartelor.pdf",
    runtimeTemplateUrl: null,
    sourceType: "downloadable_pdf",
    isOfficialSource: true,
    isOfficialSubmittable: true,
    fillMethod: "support-sheet",
    profileFieldMap: {
      last_name: "last_name", first_name: "first_name", cnp: "cnp",
      birth_date: "birth_date", city: "city", county: "county",
      id_series: "id_series", id_number: "id_number", email: "email",
    },
    requiredProfileFields: ["first_name", "last_name", "cnp", "birth_date", "city", "county", "email"],
    requiredAssets: ["signature"],
    requiredAttachments: [
      "ID card copy",
      "Completed and signed request form",
    ],
    signatureMode: "required",
    photoMode: "none",
    instructionsShort: "Submit by post or in person to Direcția Generală de Pașapoarte, Str. Obcina Mare nr. 2, București. Response within 30 days.",
    needsNotary: false,
    needsPhysicalPresence: false,
    needsAppointment: false,
    needsManualReview: false,
    outputFormats: ["pdf"],
    templateVersion: "DGP-2021",
    lastVerifiedAt: "2024-01-01",
  },

  "cerere-rneps": {
    id: "cerere-rneps",
    title: "RNEPS Data Provision Request",
    titleRo: "Cerere furnizare date din RNEPS",
    category: "rneps",
    institution: "Direcția Generală de Pașapoarte",
    sourceUrl: "https://www.mai.gov.ro/wp-content/uploads/2021/06/Cerere-furnizare-date-RNEPS.pdf",
    runtimeTemplateUrl: null,
    sourceType: "downloadable_pdf",
    isOfficialSource: true,
    isOfficialSubmittable: true,
    fillMethod: "support-sheet",
    profileFieldMap: {
      last_name: "last_name", first_name: "first_name", cnp: "cnp",
      birth_date: "birth_date", birth_place: "birth_place",
      father_name: "father_name", mother_name: "mother_name",
      address_line_1: "address_line_1", city: "city", county: "county",
      id_series: "id_series", id_number: "id_number", email: "email",
    },
    requiredProfileFields: ["first_name", "last_name", "cnp", "birth_date", "address_line_1", "email"],
    requiredAssets: ["signature"],
    requiredAttachments: [
      "ID card copy",
      "Completed and signed request",
    ],
    signatureMode: "required",
    photoMode: "none",
    instructionsShort: "Submit by post or in person to Direcția Generală de Pașapoarte. Response within 30 days per GDPR / Law 544.",
    needsNotary: false,
    needsPhysicalPresence: false,
    needsAppointment: false,
    needsManualReview: false,
    outputFormats: ["pdf"],
    templateVersion: "DGP-2021",
    lastVerifiedAt: "2024-01-01",
  },

  // ─── GENERIC FORMS ───────────────────────────────────────────────────────────

  "declaratie-proprie-raspundere": {
    id: "declaratie-proprie-raspundere",
    title: "Generic Declaration on Own Responsibility",
    titleRo: "Declarație pe proprie răspundere",
    category: "declaration",
    institution: "General use",
    sourceUrl: null,
    runtimeTemplateUrl: null,
    sourceType: "generated",
    isOfficialSource: false,
    isOfficialSubmittable: false,
    fillMethod: "support-sheet",
    profileFieldMap: {
      last_name: "last_name", first_name: "first_name", cnp: "cnp",
      birth_date: "birth_date", address_line_1: "address_line_1",
      city: "city", county: "county", id_series: "id_series", id_number: "id_number",
    },
    requiredProfileFields: ["first_name", "last_name", "cnp", "address_line_1"],
    requiredAssets: ["signature"],
    requiredAttachments: [],
    signatureMode: "required",
    photoMode: "none",
    instructionsShort: "Generic self-declaration. Fill in the subject/reason before printing. Sign before submitting.",
    needsNotary: false,
    needsPhysicalPresence: false,
    needsAppointment: false,
    needsManualReview: false,
    outputFormats: ["pdf"],
    templateVersion: "generic-v1",
    lastVerifiedAt: "2024-01-01",
  },

  "cerere-generica": {
    id: "cerere-generica",
    title: "Generic Civic Request",
    titleRo: "Cerere tip — uz general",
    category: "generic-request",
    institution: "General use",
    sourceUrl: null,
    runtimeTemplateUrl: null,
    sourceType: "generated",
    isOfficialSource: false,
    isOfficialSubmittable: false,
    fillMethod: "support-sheet",
    profileFieldMap: {
      last_name: "last_name", first_name: "first_name", cnp: "cnp",
      address_line_1: "address_line_1", city: "city", email: "email", phone: "phone",
    },
    requiredProfileFields: ["first_name", "last_name", "cnp", "address_line_1"],
    requiredAssets: [],
    requiredAttachments: [],
    signatureMode: "required",
    photoMode: "none",
    instructionsShort: "Generic request template. Fill in the subject and body before printing.",
    needsNotary: false,
    needsPhysicalPresence: false,
    needsAppointment: false,
    needsManualReview: false,
    outputFormats: ["pdf"],
    templateVersion: "generic-v1",
    lastVerifiedAt: "2024-01-01",
  },

  "fisa-pregatire-notariat": {
    id: "fisa-pregatire-notariat",
    title: "Notary Appointment — Preparation Sheet",
    titleRo: "Programare notariat — fișă pregătire",
    category: "notary",
    institution: "Birou notarial autorizat",
    sourceUrl: "https://uniuneanotarilor.ro",
    runtimeTemplateUrl: null,
    sourceType: "physical_office_only",
    isOfficialSource: false,
    isOfficialSubmittable: false,
    fillMethod: "support-sheet",
    profileFieldMap: {
      last_name: "last_name", first_name: "first_name", cnp: "cnp",
      birth_date: "birth_date", marital_status: "marital_status", address_line_1: "address_line_1",
    },
    requiredProfileFields: ["first_name", "last_name", "cnp"],
    requiredAssets: [],
    requiredAttachments: [
      "All original documents relevant to the notarial act",
      "ID card (all parties)",
      "Any existing prior agreements or contracts",
    ],
    signatureMode: "required",
    photoMode: "none",
    instructionsShort: "Contact an authorized notary office in Cluj-Napoca. Most acts require both parties present. This sheet helps you prepare your visit.",
    needsNotary: true,
    needsPhysicalPresence: true,
    needsAppointment: true,
    needsManualReview: true,
    outputFormats: ["pdf"],
    templateVersion: "preparation-only",
    lastVerifiedAt: "2024-01-01",
  },

  // ─── EXISTING TEMPLATES ──────────────────────────────────────────────────────

  "cerere-permis-conducere": {
    id: "cerere-permis-conducere",
    title: "Driving Licence Renewal — Preparation Sheet",
    titleRo: "Preschimbare permis de conducere — fișă pregătire",
    category: "driver-license",
    institution: "DRPCIV Cluj",
    sourceUrl: "https://www.drpciv.ro",
    runtimeTemplateUrl: null,
    sourceType: "official_page",
    isOfficialSource: true,
    isOfficialSubmittable: false,
    fillMethod: "support-sheet",
    profileFieldMap: {
      last_name: "last_name", first_name: "first_name", cnp: "cnp",
      birth_date: "birth_date", address_line_1: "address_line_1", city: "city",
    },
    requiredProfileFields: ["first_name", "last_name", "cnp", "birth_date"],
    requiredAssets: [],
    requiredAttachments: [
      "Valid ID (original + copy)",
      "Old driving licence",
      "Medical certificate — fișă medicală (max 6 months old)",
      "Payment — 130 RON",
    ],
    signatureMode: "required",
    photoMode: "none",
    instructionsShort: "Visit DRPCIV Cluj, Str. Fabricii de Zahăr nr. 51. Tuesday/Wednesday afternoons are least crowded.",
    needsNotary: false,
    needsPhysicalPresence: true,
    needsAppointment: false,
    needsManualReview: false,
    outputFormats: ["pdf"],
    templateVersion: "current",
    lastVerifiedAt: "2024-01-01",
  },

  "cerere-certificat-fiscal-anaf": {
    id: "cerere-certificat-fiscal-anaf",
    title: "ANAF Fiscal Certificate Request",
    titleRo: "Cerere certificat de atestare fiscală",
    category: "anaf",
    institution: "ANAF Cluj-Napoca",
    sourceUrl: "https://static.anaf.ro/static/10/Anaf/formulare/Cerere_certificat_atestare_fiscala_PF_OPANAF_3654_2015.pdf",
    runtimeTemplateUrl: null,
    sourceType: "downloadable_pdf",
    isOfficialSource: true,
    isOfficialSubmittable: true,
    fillMethod: "support-sheet",
    profileFieldMap: {
      last_name: "last_name", first_name: "first_name", cnp: "cnp",
      address_line_1: "address_line_1", city: "city", county: "county",
    },
    requiredProfileFields: ["first_name", "last_name", "cnp", "address_line_1"],
    requiredAssets: [],
    requiredAttachments: ["Valid ID", "Signed request form"],
    signatureMode: "required",
    photoMode: "none",
    instructionsShort: "Submit online via SPV at anaf.ro. Issued in 5 working days online.",
    needsNotary: false,
    needsPhysicalPresence: false,
    needsAppointment: false,
    needsManualReview: false,
    onlineUrl: "https://www.anaf.ro/anaf/internet/RO/cont-curent-spv",
    outputFormats: ["pdf"],
    templateVersion: "OPANAF-3654-2015",
    lastVerifiedAt: "2024-01-01",
  },

  "cerere-inregistrare-srl": {
    id: "cerere-inregistrare-srl",
    title: "Company Registration — SRL",
    titleRo: "Cerere înregistrare SRL",
    category: "business-registration",
    institution: "Registrul Comerțului Cluj",
    sourceUrl: "https://portal.onrc.ro",
    runtimeTemplateUrl: null,
    sourceType: "official_page",
    isOfficialSource: true,
    isOfficialSubmittable: false,
    fillMethod: "support-sheet",
    profileFieldMap: {
      last_name: "last_name", first_name: "first_name", cnp: "cnp",
      address_line_1: "address_line_1", city: "city", county: "county",
    },
    requiredProfileFields: ["first_name", "last_name", "cnp"],
    requiredAssets: [],
    requiredAttachments: [
      "Act constitutiv (Articles of Association) — notarized or simple written form",
      "Dovadă sediu social (registered office proof)",
      "ID of all associates and administrators",
      "Cazier judiciar (criminal record) for administrators",
      "Specimen de semnătură — notarized",
      "Payment — 200 RON",
    ],
    signatureMode: "required",
    photoMode: "none",
    instructionsShort: "Submit online at portal.onrc.ro. Walk-in: Str. Horea nr. 65.",
    needsNotary: true,
    needsPhysicalPresence: false,
    needsAppointment: false,
    needsManualReview: true,
    onlineUrl: "https://portal.onrc.ro",
    outputFormats: ["pdf"],
    templateVersion: "2022",
    lastVerifiedAt: "2024-01-01",
  },

  "cerere-divort-notariat": {
    id: "cerere-divort-notariat",
    title: "Divorce — Notary Route Preparation Sheet",
    titleRo: "Divorț notarial — fișă pregătire",
    category: "divorce-notary",
    institution: "Birou notarial Cluj-Napoca",
    sourceUrl: null,
    runtimeTemplateUrl: null,
    sourceType: "physical_office_only",
    isOfficialSource: false,
    isOfficialSubmittable: false,
    fillMethod: "support-sheet",
    profileFieldMap: {
      last_name: "last_name", first_name: "first_name", cnp: "cnp",
      birth_date: "birth_date", marital_status: "marital_status", address_line_1: "address_line_1",
    },
    requiredProfileFields: ["first_name", "last_name", "cnp"],
    requiredAssets: [],
    requiredAttachments: [
      "Marriage certificate (original)",
      "Both spouses' ID cards",
      "Birth certificates of any minor children",
      "Notarized parental agreement (if children involved)",
    ],
    signatureMode: "required",
    photoMode: "none",
    instructionsShort: "Both spouses appear in person before any authorized notary in Cluj. 30-day reflection period applies.",
    needsNotary: true,
    needsPhysicalPresence: true,
    needsAppointment: true,
    needsManualReview: true,
    outputFormats: ["pdf"],
    templateVersion: "preparation-only",
    lastVerifiedAt: "2024-01-01",
  },

  "cerere-cazier-judiciar": {
    id: "cerere-cazier-judiciar",
    title: "Criminal Record Certificate",
    titleRo: "Cazier judiciar",
    category: "police",
    institution: "IPJ Cluj / e-cazier",
    sourceUrl: "https://e-cazier.mai.gov.ro",
    runtimeTemplateUrl: null,
    sourceType: "online_form",
    isOfficialSource: true,
    isOfficialSubmittable: false,
    fillMethod: "support-sheet",
    profileFieldMap: {
      last_name: "last_name", first_name: "first_name", cnp: "cnp",
    },
    requiredProfileFields: ["first_name", "last_name", "cnp"],
    requiredAssets: [],
    requiredAttachments: ["Valid ID only"],
    signatureMode: "none",
    photoMode: "none",
    instructionsShort: "Use e-cazier.mai.gov.ro online — instant result. In person: IPJ Cluj, Calea Dorobanților nr. 9.",
    needsNotary: false,
    needsPhysicalPresence: false,
    needsAppointment: false,
    needsManualReview: false,
    onlineUrl: "https://e-cazier.mai.gov.ro",
    outputFormats: ["pdf"],
    templateVersion: "online",
    lastVerifiedAt: "2024-01-01",
  },

  "cerere-asigurare-sanatate": {
    id: "cerere-asigurare-sanatate",
    title: "Health Insurance Self-Declaration",
    titleRo: "Declarație asigurare CJAS",
    category: "health-insurance",
    institution: "CJAS Cluj",
    sourceUrl: "https://cnas.ro",
    runtimeTemplateUrl: null,
    sourceType: "official_page",
    isOfficialSource: true,
    isOfficialSubmittable: false,
    fillMethod: "support-sheet",
    profileFieldMap: {
      last_name: "last_name", first_name: "first_name", cnp: "cnp", address_line_1: "address_line_1",
    },
    requiredProfileFields: ["first_name", "last_name", "cnp"],
    requiredAssets: [],
    requiredAttachments: ["Valid ID", "Proof of uninsured status"],
    signatureMode: "required",
    photoMode: "none",
    instructionsShort: "Check status at portal.cnas.ro. Submit at CJAS Cluj, Str. Constanța nr. 5.",
    needsNotary: false,
    needsPhysicalPresence: false,
    needsAppointment: false,
    needsManualReview: false,
    onlineUrl: "https://portal.cnas.ro",
    outputFormats: ["pdf"],
    templateVersion: "2021",
    lastVerifiedAt: "2024-01-01",
  },
};

export function getTemplate(docId) {
  return templateRegistry[docId] || null;
}

export function getTemplatesForProcedure(procedureKey) {
  return Object.values(templateRegistry).filter(t =>
    t.category === procedureKey || t.id.includes(procedureKey)
  );
}

export const procedureDocumentMap = {
  "id-renewal":        ["cerere-ci-reinnoire"],
  "lost-id":           ["cerere-ci-pierdut"],
  "domicile-change":   ["cerere-ci-domiciliu"],
  "passport":          ["cerere-pasaport"],
  "passport-renewal":  ["cerere-pasaport"],
  "passport-urgent":   ["cerere-pasaport-urgent"],
  "passport-history":  ["cerere-istoric-pasaport"],
  "rneps":             ["cerere-rneps"],
  "declaration":       ["declaratie-proprie-raspundere"],
  "generic-request":   ["cerere-generica"],
  "notary":            ["fisa-pregatire-notariat"],
  "driver-license":    ["cerere-permis-conducere"],
  "anaf-tax":          ["cerere-certificat-fiscal-anaf"],
  "business-registration": ["cerere-inregistrare-srl"],
  "divorce":           ["cerere-divort-notariat"],
  "criminal-record":   ["cerere-cazier-judiciar"],
  "health-insurance":  ["cerere-asigurare-sanatate"],
};