/**
 * GeneratedDocumentsCenter — Full hub of all documents generated by the current user.
 * Shows stale status, drive status, download/regenerate controls.
 */
import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import {
  Archive, Loader2, CheckCircle2, AlertTriangle, RefreshCw,
  FileText, ChevronDown, ChevronUp, Search
} from 'lucide-react';
import { base44 } from '@/api/base44Client';
import { Input } from '@/components/ui/input';
import GeneratedDocumentCard from './GeneratedDocumentCard';
import { generateDocument } from '@/lib/documents/documentGenerationService';
import { getTemplate } from '@/lib/documents/templateRegistry';
import { isDocumentStale } from '@/lib/documents/documentGenerationService';

export default function GeneratedDocumentsCenter({ currentProfile }) {
  const [search, setSearch] = useState('');
  const [expanded, setExpanded] = useState(true);
  const [regeneratingId, setRegeneratingId] = useState(null);
  const queryClient = useQueryClient();

  const { data: docs = [], isLoading } = useQuery({
    queryKey: ['generated-docs-center'],
    queryFn: async () => {
      const user = await base44.auth.me();
      if (!user?.email) return [];
      return base44.entities.GeneratedDocument.filter(
        { user_id: user.email },
        '-created_date',
        50
      );
    },
  });

  const handleRegenerate = async (doc) => {
    setRegeneratingId(doc.id);
    const template = getTemplate(doc.document_key);
    if (!template) { setRegeneratingId(null); return; }

    await base44.entities.GeneratedDocument.delete(doc.id);
    const docResult = {
      template,
      status: 'ready',
      missing_assets: [],
      special_instruction_labels: doc.instruction_labels || [],
    };
    await generateDocument({
      docResult,
      profile: currentProfile,
      caseId: doc.case_id,
      procedureKey: doc.procedure_key,
    });
    queryClient.invalidateQueries({ queryKey: ['generated-docs-center'] });
    setRegeneratingId(null);
  };

  const filtered = docs.filter(d => {
    if (!search.trim()) return true;
    const q = search.toLowerCase();
    return (
      d.document_title?.toLowerCase().includes(q) ||
      d.procedure_key?.toLowerCase().includes(q) ||
      d.source_label?.toLowerCase().includes(q)
    );
  });

  const staleCount = docs.filter(d => isDocumentStale(d, currentProfile)).length;
  const readyCount = docs.filter(d => d.status === 'ready').length;
  const driveCount = docs.filter(d => d.drive_upload_status === 'uploaded').length;

  return (
    <div className="mt-12 rounded-3xl border border-white/8 bg-white/[0.02] overflow-hidden">
      {/* Header */}
      <button
        onClick={() => setExpanded(!expanded)}
        className="w-full flex items-center justify-between p-5 hover:bg-white/[0.02] transition-colors"
      >
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 rounded-xl bg-accent/15 flex items-center justify-center">
            <Archive className="w-4 h-4 text-accent" />
          </div>
          <div className="text-left">
            <h3 className="text-sm font-bold text-white">Generated Documents Center</h3>
            <p className="text-[11px] text-slate-500 mt-0.5">
              {docs.length} document{docs.length !== 1 ? 's' : ''} generated
              {staleCount > 0 && ` · ${staleCount} outdated`}
            </p>
          </div>
        </div>
        <div className="flex items-center gap-3">
          {staleCount > 0 && (
            <span className="flex items-center gap-1 text-[10px] text-warning bg-warning/10 px-2 py-1 rounded-full border border-warning/20">
              <RefreshCw className="w-3 h-3" /> {staleCount} stale
            </span>
          )}
          {readyCount > 0 && (
            <span className="flex items-center gap-1 text-[10px] text-success bg-success/10 px-2 py-1 rounded-full border border-success/20">
              <CheckCircle2 className="w-3 h-3" /> {readyCount} ready
            </span>
          )}
          {driveCount > 0 && (
            <span className="flex items-center gap-1 text-[10px] text-blue-400 bg-blue-500/10 px-2 py-1 rounded-full border border-blue-500/20">
              ☁ {driveCount} in Drive
            </span>
          )}
          {expanded ? <ChevronUp className="w-4 h-4 text-slate-500" /> : <ChevronDown className="w-4 h-4 text-slate-500" />}
        </div>
      </button>

      <AnimatePresence>
        {expanded && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            className="overflow-hidden"
          >
            <div className="px-5 pb-5 border-t border-white/5">
              {isLoading ? (
                <div className="flex items-center justify-center py-8">
                  <Loader2 className="w-5 h-5 text-primary animate-spin" />
                </div>
              ) : docs.length === 0 ? (
                <div className="text-center py-8">
                  <FileText className="w-8 h-8 text-slate-700 mx-auto mb-3" />
                  <p className="text-slate-500 text-sm">No documents generated yet</p>
                  <p className="text-slate-600 text-xs mt-1">Use the search above to start generating documents</p>
                </div>
              ) : (
                <>
                  {/* Search */}
                  {docs.length > 3 && (
                    <div className="relative my-4">
                      <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-slate-500" />
                      <Input
                        value={search}
                        onChange={e => setSearch(e.target.value)}
                        placeholder="Search generated documents..."
                        className="pl-9 h-9 bg-white/[0.03] border-white/10 text-white placeholder:text-slate-600 rounded-xl text-xs"
                      />
                    </div>
                  )}

                  <div className="space-y-3 mt-4">
                    <AnimatePresence>
                      {filtered.map(doc => (
                        <div key={doc.id} className="relative">
                          {regeneratingId === doc.id && (
                            <div className="absolute inset-0 z-10 bg-background/70 backdrop-blur-sm rounded-2xl flex items-center justify-center">
                              <Loader2 className="w-5 h-5 text-primary animate-spin" />
                            </div>
                          )}
                          <GeneratedDocumentCard
                            doc={doc}
                            currentProfile={currentProfile}
                            onRegenerate={handleRegenerate}
                            showProcedure
                          />
                        </div>
                      ))}
                    </AnimatePresence>
                    {filtered.length === 0 && search && (
                      <p className="text-center text-slate-600 text-xs py-4">
                        No documents matching "{search}"
                      </p>
                    )}
                  </div>
                </>
              )}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}